spring:
  application:
    name: lv2-final-mission
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:database
    username: sa
    password: 1234

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

jwt:
  secret-key: "Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E="
  validity-in-milliseconds: 3600000

api:
  randommer:
    api-key: bd7de2187f414b49aef04634c990fb9c
